# Use the published dependency image by default. Local builds can override it
# with a locally built blocksci-cj tag.
ARG BLOCKSCI_BASE_IMAGE=ghcr.io/ondrejman/blocksci-cj:latest
FROM ${BLOCKSCI_BASE_IMAGE}

ARG NTHREADS=1
ENV NTHREADS=${NTHREADS}

# Set the working directory inside the container
WORKDIR /mnt

# Copy the local 'blocksci' folder into the image at /mnt/blocksci
COPY . /mnt/blocksci

RUN cd /mnt/blocksci/ && \
    SKIP_JUPYTER=1 ./build.sh

# Set the entrypoint to bash as you had in your command
ENTRYPOINT ["/bin/bash"]
