# Use your existing image as the base
FROM ghcr.io/ondrejman/blocksci-cj:latest

ARG NTHREADS=1
ENV NTHREADS=${NTHREADS}

# Set the working directory inside the container
WORKDIR /mnt

# Copy the local 'blocksci' folder into the image at /mnt/blocksci
COPY . /mnt/blocksci

RUN cd /mnt/blocksci/ && \
    SKIP_JUPYTER=1 ./build.sh && \
    uv pip uninstall crypto && \
    uv pip install pycryptodome

# Set the entrypoint to bash as you had in your command
ENTRYPOINT ["/bin/bash"]
